#index:
#    path: /
#    controller: App\Controller\DefaultController::index
botman_webhook:
  path: /webhook
  methods: [GET,POST]
  defaults:
    _controller: App\Controller\BotManController::botManWebHook

dialog:
  path: /dialog
  methods: [GET,POST]
  defaults:
    _controller: App\Controller\BotManController::testDialogFlow

