#index:
#    path: /
#    controller: App\Controller\DefaultController::index
botman_webhook:
  path: /botman/webhook
  methods: [GET,POST]
  defaults:
    _controller: App\Controller\botmanController::botmanWebhook

dialog:
  path: /dialog
  methods: [GET,POST]
  defaults:
    _controller: App\Controller\botmanController::testDialogFlow

