#index:
#    path: /
#    controller: App\Controller\DefaultController::index
botman_webhook:
  path: /botman/webhook
  methods: [GET]
  defaults:
    _controller: App\Controller\botmanController::botmanWebhook